In [288]:
#!/usr/bin/env python3
import csv
import sys
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import os
import os.path
import datetime
from matplotlib import rc
import pathlib
import glob

out_dir = "out/"
os.makedirs(out_dir, exist_ok=True)

In [289]:
# import csv files
import_dir = "//172.25.0.195/fte_data (東日本)/【東京支社】/1.計画物件/3一般企業/ファーストチョイス㈱/ハンバーグフリーザー/HANEW本社監査指摘事項/送受信/Package1/SOUSA"
output_dir = "C:/Users/0296/TAKAHASHI(Local)/firstChiceDataAnalysis"

os.chdir(import_dir)
csv_list = glob.glob("AAM00021_*.CSV")
# print('csv_list[0]=',csv_list[0])
# csv_list

In [290]:
col_name = range(1,11,1)
df = pd.read_csv(csv_list[0], names = col_name, encoding="cp932", delimiter=",", dtype="object")

record_num = int(df_data.iloc[0,1])
print("Record number = ",record_num)
header_num = 15
_df = df[header_num:]
_df

Record number =  200

,1,2,3,4,5,6,7,8,9,10
15,0,0,109,108:警報解除ｽｲｯﾁ 操作履歴,R,2023/1/11 8:18,2023/1/11 8:18,****/**/** **:**:**,1,1
16,0,0,109,108:警報解除ｽｲｯﾁ 操作履歴,R,2023/1/11 8:23,2023/1/11 8:23,****/**/** **:**:**,1,1
17,0,0,108,107:警報停止ｽｲｯﾁ 操作履歴,R,2023/1/11 8:23,2023/1/11 8:23,****/**/** **:**:**,1,1
18,0,0,109,108:警報解除ｽｲｯﾁ 操作履歴,R,2023/1/11 8:23,2023/1/11 8:24,****/**/** **:**:**,1,1
19,0,0,93,092:冷却設定操作履歴,R,2023/1/11 9:25,2023/1/11 9:25,****/**/** **:**:**,1,1
...,...,...,...,...,...,...,...,...,...,...
210,0,0,112,111:商品選択2,R,2023/1/19 18:04,2023/1/19 18:04,****/**/** **:**:**,1,1
211,0,0,113,112:商品選択3,R,2023/1/19 18:35,2023/1/19 18:35,****/**/** **:**:**,1,1
212,0,0,105,104:停止ｽｲｯﾁ操作履歴,R,2023/1/19 19:02,2023/1/19 19:02,****/**/** **:**:**,1,1
213,0,0,103,102:洗浄 ｾﾚｸﾀｽｲｯﾁ操作履歴,O,2023/1/19 19:04,****/**/** **:**:**,****/**/** **:**:**,1,1
214,0,0,104,103:運転ｽｲｯﾁ操作履歴,R,2023/1/19 19:05,2023/1/19 19:05,****/**/** **:**:**,1,1

In [291]:
#1,2,8,9,10列削除
_df = _df.drop([1,2,8,9,10], axis=1)
_df

       3                        4  5                6                    7
15   109      108:警報解除ｽｲｯﾁ   操作履歴  R   2023/1/11 8:18       2023/1/11 8:18
16   109      108:警報解除ｽｲｯﾁ   操作履歴  R   2023/1/11 8:23       2023/1/11 8:23
17   108      107:警報停止ｽｲｯﾁ   操作履歴  R   2023/1/11 8:23       2023/1/11 8:23
18   109      108:警報解除ｽｲｯﾁ   操作履歴  R   2023/1/11 8:23       2023/1/11 8:24
19    93             092:冷却設定操作履歴  R   2023/1/11 9:25       2023/1/11 9:25
..   ...                      ... ..              ...                  ...
210  112                111:商品選択2  R  2023/1/19 18:04      2023/1/19 18:04
211  113                112:商品選択3  R  2023/1/19 18:35      2023/1/19 18:35
212  105           104:停止ｽｲｯﾁ操作履歴  R  2023/1/19 19:02      2023/1/19 19:02
213  103   102:洗浄    ｾﾚｸﾀｽｲｯﾁ操作履歴  O  2023/1/19 19:04  ****/**/** **:**:**
214  104           103:運転ｽｲｯﾁ操作履歴  R  2023/1/19 19:05      2023/1/19 19:05

[200 rows x 5 columns]

In [292]:
list = ['101',]
drop_list = []
for i in range(0,record_num):
    if _df.iloc[i,0] in list:
        continue
    else:
        drop_list.append(i)

# print(drop_list)
_df = _df.drop(_df.index[drop_list])
_df

       3                        4  5                6                7
34   101   100:冷却    ｾﾚｸﾀｽｲｯﾁ操作履歴  R   2023/1/12 7:03  2023/1/12 21:14
54   101   100:冷却    ｾﾚｸﾀｽｲｯﾁ操作履歴  R   2023/1/13 7:03  2023/1/13 17:35
63   101   100:冷却    ｾﾚｸﾀｽｲｯﾁ操作履歴  R   2023/1/14 7:25  2023/1/14 14:14
90   101   100:冷却    ｾﾚｸﾀｽｲｯﾁ操作履歴  R  2023/1/15 11:19  2023/1/15 13:43
109  101   100:冷却    ｾﾚｸﾀｽｲｯﾁ操作履歴  R   2023/1/16 7:03  2023/1/16 19:27
125  101   100:冷却    ｾﾚｸﾀｽｲｯﾁ操作履歴  R   2023/1/17 7:02  2023/1/17 19:12
144  101   100:冷却    ｾﾚｸﾀｽｲｯﾁ操作履歴  R   2023/1/18 7:03  2023/1/18 19:13
150  101   100:冷却    ｾﾚｸﾀｽｲｯﾁ操作履歴  R  2023/1/18 19:27  2023/1/18 19:27
152  101   100:冷却    ｾﾚｸﾀｽｲｯﾁ操作履歴  R  2023/1/18 19:27  2023/1/18 19:27
156  101   100:冷却    ｾﾚｸﾀｽｲｯﾁ操作履歴  R   2023/1/19 7:07  2023/1/19 19:04

In [293]:
os.chdir(output_dir)
_df.to_csv("./out/sample02.csv", encoding="shift_jis", header=False, mode='a')

In [294]:
_df.iloc[0,2]

'R'

In [295]:
data = {'COMMENT_NO':[], 'COMMENT':[], 'STATUS':[], 'OCCURRED':[], 'RESTORED':[], 'OT':[]}
df0 = pd.DataFrame(data)
df0['OCCURRED'] = (pd.to_datetime(df0['OCCURRED'])).dt.round("min")
df0['RESTORED'] = (pd.to_datetime(df0['RESTORED'])).dt.round("min")

for csv in csv_list:
    os.chdir(import_dir)
    col_name = range(1,11,1)
    df = pd.read_csv(csv, names = col_name, encoding="cp932", delimiter=",", dtype="object")
    
    #headerおよび不要な列削除
    df = df[15:]
    df = df.drop([1,2,8,9,10], axis=1)
    
    drop_list = []
    for i in range(0,record_num):
        if df.iloc[i,0]=='101' and df.iloc[i,2] == 'R':
            continue
        else:
            drop_list.append(i)
    df = df.drop(df.index[drop_list])
    
    df[6] = (pd.to_datetime(df[6])).dt.round("min")
    df[7] = (pd.to_datetime(df[7])).dt.round("min")
    df[8] = df[7] - df[6]
    
    # 3時間以下をフィルタリング
    drop_list = []
    for i in range(0,len(_df)):
        if int((df.iloc[i,5]).seconds)>= 3*3600:
            continue
        else:
            drop_list.append(i)
            
    df = df.drop(df.index[drop_list])
    
    os.chdir(output_dir)
    t_delta = datetime.timedelta(hours=9)
    JST = datetime.timezone(t_delta, 'JST')
    now = datetime.datetime.now(JST)
    d = now.strftime('%Y%m%d')
    
    df0 = pd.concat([df0,df])
    # _df.to_csv(out_dir+"sample01_{0}.csv".format(d), encoding="shift_jis", header=False, mode='a')

df0 = df0.drop_duplicates(subset='OCCURRED')
df0.to_csv(out_dir+"02_{0}.csv".format(d), encoding="shift_jis", header=False, mode='a')

print('end')

IndexError: index 9 is out of bounds for axis 0 with size 9